# Generated by Django 2.1.15 on 2020-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('iso3', models.CharField(max_length=10, verbose_name='iso3')),
                ('phoneCode', models.CharField(max_length=10, verbose_name='Phone Code')),
                ('title', models.CharField(max_length=5000, verbose_name='Title')),
                ('fullTitle', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Full Title')),
                ('address', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Address')),
                ('cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latt', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('rq_time', models.IntegerField(blank=True, null=True, verbose_name='Require Time')),
                ('vis_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visit Time Range')),
                ('vis_time_from', models.IntegerField(blank=True, null=True, verbose_name='Visit Time From')),
                ('vis_time_to', models.IntegerField(blank=True, null=True, verbose_name='Visit Time To')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provice')),
                ('City', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Attractions',
                'ordering': ('latt', 'long'),
            },
        ),
    ]
