# Generated by Django 2.1.15 on 2020-03-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneCode', models.CharField(max_length=10, verbose_name='Phone Code')),
                ('title', models.CharField(max_length=5000, verbose_name='Title')),
                ('fullTitle', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Full Title')),
                ('address', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Address')),
                ('cost', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('latt', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('rq_time', models.IntegerField(blank=True, null=True, verbose_name='Require Time')),
                ('vis_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Visit Time Range')),
                ('vis_time_from', models.IntegerField(blank=True, null=True, verbose_name='Visit Time From')),
                ('vis_time_to', models.IntegerField(blank=True, null=True, verbose_name='Visit Time To')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': '3_Attractions',
                'ordering': ('latt', 'long'),
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City Name')),
                ('phoneCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Code')),
                ('latt', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name_plural': '2_City',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('iso3', models.CharField(blank=True, max_length=10, null=True, verbose_name='IOS3')),
                ('phoneCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Code')),
            ],
            options={
                'verbose_name_plural': '0_Country',
            },
        ),
        migrations.CreateModel(
            name='distance_mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecl_dist', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Euclidean Distance')),
                ('len_meter', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Meters')),
                ('len_time', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Time')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='plan.attractions')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_mat', to='plan.attractions')),
            ],
            options={
                'verbose_name_plural': '6_Distance matrix',
            },
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Province Name')),
                ('phoneCode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Code')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.country')),
            ],
            options={
                'verbose_name_plural': '1_Province',
            },
        ),
        migrations.CreateModel(
            name='travelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': '4_Travel Types',
            },
        ),
        migrations.AddField(
            model_name='distance_mat',
            name='travel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.travelType'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.province'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.city'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.country'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.province'),
        ),
    ]
