# Generated by Django 2.1.15 on 2020-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='like_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='view_no',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Views'),
        ),
    ]
