# Generated by Django 2.1.15 on 2020-03-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attractions',
            old_name='City',
            new_name='city',
        ),
    ]
