# Generated by Django 2.1.15 on 2020-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='safarzoon_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id in safarzoon.com'),
        ),
        migrations.AddField(
            model_name='city',
            name='safarzoon_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id in safarzoon.com'),
        ),
        migrations.AddField(
            model_name='country',
            name='safarzoon_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id in safarzoon.com'),
        ),
        migrations.AddField(
            model_name='province',
            name='safarzoon_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id in safarzoon.com'),
        ),
    ]
