# Generated by Django 2.1.15 on 2020-03-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance_mat',
            name='ecl_dist',
            field=models.FloatField(blank=True, null=True, verbose_name='Euclidean Distance'),
        ),
    ]
