# Generated by Django 2.1.15 on 2020-03-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200312_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='distance_mat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecl_dist', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Euclidean Distance')),
                ('len_meter', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Meters')),
                ('len_time', models.FloatField(blank=True, null=True, verbose_name='Lenght Of Time')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='plan.attractions')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_mat', to='plan.attractions')),
            ],
            options={
                'verbose_name_plural': '?????',
            },
        ),
        migrations.CreateModel(
            name='travelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': '??? ??????',
            },
        ),
        migrations.AddField(
            model_name='distance_mat',
            name='travel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.travelType'),
        ),
    ]
