# Generated by Django 2.1.15 on 2020-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='tags',
        ),
    ]
