# Generated by Django 2.1.15 on 2020-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_attraction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='plan.tags'),
        ),
    ]
