# Generated by Django 2.1.15 on 2020-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('city', 'airport_en'), 'verbose_name_plural': '3 Airports'},
        ),
        migrations.AlterModelOptions(
            name='attractions',
            options={'ordering': ('latt', 'long'), 'verbose_name_plural': '4 Attractions'},
        ),
        migrations.AlterModelOptions(
            name='traveltype',
            options={'verbose_name_plural': '5 Travel Types'},
        ),
        migrations.AddField(
            model_name='attractions',
            name='type',
            field=models.IntegerField(choices=[(0, '???????'), (1, '??????')], default=0, verbose_name='Selection Type'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='phoneCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Code'),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Title'),
        ),
    ]
