# Generated by Django 2.1.15 on 2020-03-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200322_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_details',
            name='from_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attractions',
            name='type',
            field=models.IntegerField(choices=[(0, 'Optionaly'), (1, 'Necessary')], default=0, verbose_name='Selection Type'),
        ),
    ]
