# Generated by Django 2.1.15 on 2020-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_attraction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance_mat',
            name='rout',
            field=models.TextField(blank=True, null=True, verbose_name='Routing Json'),
        ),
    ]
