# Generated by Django 2.1.15 on 2020-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20200323_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_details',
            old_name='from_date',
            new_name='dist_to',
        ),
        migrations.AddField(
            model_name='plan_details',
            name='from_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
