# Generated by Django 2.1.15 on 2020-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20200323_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Tags'),
        ),
    ]
