# Generated by Django 2.1.15 on 2020-03-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_attractions_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag Title')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.RemoveField(
            model_name='attractions',
            name='tags',
        ),
        migrations.AddField(
            model_name='attractions',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='plan.tags'),
        ),
    ]
