# Generated by Django 2.1.15 on 2020-03-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_auto_20200324_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractions',
            name='tags',
        ),
    ]
