# Generated by Django 2.1.15 on 2020-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_remove_attractions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='plan.tags'),
        ),
    ]
