# Generated by Django 2.1.15 on 2020-04-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20200403_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='type',
            field=models.IntegerField(choices=[(0, 'Attraction'), (1, 'Fooding'), (2, 'Resting'), (3, 'Healthing'), (4, 'Others')], default=0, verbose_name='Selection Type'),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='type',
            field=models.IntegerField(choices=[(0, 'Attraction'), (1, 'Fooding'), (2, 'Resting'), (3, 'Healthing'), (4, 'Others')], default=1, verbose_name='Selection Type'),
        ),
    ]
