# Generated by Django 2.1.15 on 2020-04-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0017_auto_20200403_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_details',
            name='point',
            field=models.IntegerField(),
        ),
    ]
