# Generated by Django 2.1.15 on 2020-04-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20200404_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_details',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.attractions'),
        ),
    ]
