# Generated by Django 2.1.15 on 2020-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20200404_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day Of Tour'),
        ),
    ]
