# Generated by Django 2.1.15 on 2020-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1000, verbose_name='Type')),
                ('details', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Details')),
                ('title', models.CharField(max_length=5000, verbose_name='Title')),
                ('location', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Location')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'points',
                'ordering': ('type', 'details', 'location'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('details',)},
        ),
    ]
